name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build-gpu:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/ml-opgave:gpu-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            processor=gpu

  build-cpu:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/ml-opgave:cpu-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            processor=cpu